// apps/sb-react-web/src/app/app.tsx
import styled from 'styled-components';
import NxWelcome from './nx-welcome';
import { RNHighScores } from '@betsson-sportsbook-monorepo/sb-ui-components';

const StyledApp = styled.div`
  // Your style here
`;

export function App() {
  return (
    <StyledApp>
      <NxWelcome title="sb-react-web" />
    </StyledApp>
  );
}

export default App;

// apps/sb-angular-web/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'betsson-sportsbook-monorepo-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  title = 'sb-angular-web';
}

<betsson-sportsbook-monorepo-nx-welcome></betsson-sportsbook-monorepo-nx-welcome>
