// apps/sb-angular-web/src/giphy-search/components/giphy-search.component.ts
import { Component, OnInit } from '@angular/core';
import { Store } from '@ngrx/store';
import { GiphyItem, searchGiphiesStart, selectGiphies } from '@betsson-sportsbook-monorepo/data-access-giphy';
import { Observable } from 'rxjs';
import '../../../../../libs/sb-ui-components/src/lib/custom-GifyItem.js';

@Component({
  // eslint-disable-next-line @angular-eslint/component-selector
  selector: 'app-giphy-search',
  template: `
    <input type="text" (keyup)="handleInput($event)" />
    <section *ngIf="!isEmpty" class="giphy-container">
      <giphy-item-wrapper
        *ngFor="let giphy of giphies$ | async; index as i;"
        [imageUrl]="giphy.images.fixed_height_small.url">
      </giphy-item-wrapper>
    </section>
  `
})
export class GiphySearchComponent {
  giphies$: Observable<Array<GiphyItem>>
  isEmpty = true;
  constructor(private store: Store) {
    this.giphies$ = store.select(selectGiphies)
  }

  handleInput(e: Event) {
    if ((e.target as HTMLInputElement).value.length === 0) {
      this.isEmpty = true
    } else {
      this.isEmpty = false
      this.store.dispatch(searchGiphiesStart((e.target as HTMLInputElement).value))
    }
  }
}

// apps/sb-react-web/src/app/giphy-search/GiphySearch.tsx
import { useDispatch, useSelector } from 'react-redux';
import { GiphyItem, searchGiphiesStart, selectGiphies } from '@betsson-sportsbook-monorepo/data-access-giphy';
import { useState } from 'react';
import '../../../../../libs/sb-ui-components/src/lib/custom-GifyItem.js'

export function GiphySearch() {
  const dispatch = useDispatch()
  const [isEmpty, setEmpty] = useState(true)
  const giphies = useSelector(selectGiphies)

  return (
    <div>
      <input className='input-field' onKeyUp={handleInput} />
      {!isEmpty && (
        <section className="gify-item_container">
          {giphies.map((gify: GiphyItem) => {
            return (
              <gify-item
                key={gify.id}
                // @ts-ignore
                imageurl={gify.images.fixed_height_small.url}
              />
            )
          })}
        </section>
      )}
    </div>
  );

  function handleInput(e: React.KeyboardEvent<HTMLInputElement>) {
    if ((e.target as HTMLInputElement).value.length === 0) {
      return setEmpty(true)
    }
    setEmpty(false)
    dispatch(searchGiphiesStart((e.target as HTMLInputElement).value))
  }
}

export default GiphySearch;
